# Este es un workflow básico para ayudarte a comenzar con Actions

name: CI

# Controla cuándo se ejecutará el workflow
on:
  # Activa el workflow en eventos de push o pull request, pero solo para la rama "main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Permite ejecutar este workflow manualmente desde la pestaña de Actions
  workflow_dispatch:

# Un run de workflow está compuesto por uno o más jobs que pueden ejecutarse de manera secuencial o en paralelo
jobs:
  # Este workflow contiene un solo job llamado "build"
  build:
    # El tipo de runner en el que se ejecutará el job
    runs-on: ubuntu-latest

    # Los steps representan una secuencia de tareas que se ejecutarán como parte del job
    steps:
      # Realiza el checkout de tu repositorio bajo $GITHUB_WORKSPACE, para que tu job pueda acceder a él
      - uses: actions/checkout@v4

      # Ejecuta un solo comando usando la shell del runner
      - name: Ejecutar un script de una sola línea
        run: echo Hello, world!

      # Ejecuta un conjunto de comandos usando la shell del runner
      - name: Ejecutar un script de múltiples líneas
        run: |
          echo Agrega otras acciones para construir,
          echo probar y desplegar tu proyecto.
